env:
  browser: true
  es2020: true
extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-explicit-any': 0
ignorePatterns:
  - dist/
  - compiled/
  - imports/
